name: Manual Test Deploy to Yandex S3

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.YC_S3_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.YC_S3_SECRET_KEY }}
          aws configure set default.region ru-central1

      - name: Upload Test File
        run: |
          echo "Привет! Тест деплоя прошел успешно!" > test.txt
          aws --endpoint-url=https://yandexcloud.net s3 cp test.txt s3://://vn-13.com --acl public-read
